
# .github/workflows/main.yml dosyanızın içeriği

name: Otomatik M3U Oluşturucu

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Depoya yazma izni (bir önceki hata için eklenmişti, kalmalı)
    permissions:
      contents: write

    steps:
      # 1. Depodaki kodları sunucuya indirir
      - uses: actions/checkout@v3

      # 2. BURAYA DİKKAT:
      # output.m3u dosyasını oluşturan veya güncelleyen komutlarınız
      # bu adımda yer almalıdır. Örneğin:
      # - name: M3U dosyasını oluştur
      #   run: python ./scripts/generate_m3u.py

      # 3. Değişiklikleri kontrol et, commit at ve push yap
      - name: Değişiklikleri Commit ve Push yap
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Oluşturulan dosyayı ekle
          git add output.m3u
          
          # Git'in izlediği dosyalarda bir değişiklik olup olmadığını kontrol et
          # Eğer değişiklik yoksa, sonraki komutları çalıştırma ve işi bitir.
          if git diff --staged --quiet; then
            echo "Değişiklik bulunamadı, çıkılıyor."
            exit 0
          fi
          
          # Sadece değişiklik varsa commit at ve push yap
          git commit -m "Otomatik M3U çıktısını güncelle [skip ci]"
          git push