name: Generate M3U Lists

on:
  # Otomatik çalıştırma: her 12 saatte bir
  schedule:
    - cron: '0 */12 * * *'
  # Manuel tetikleme için
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Push işlemi için gerekli izin

    steps:
    # 1. Depoyu indir
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. PHP 8.2 kur
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    # 3. PHP scriptlerini sırayla çalıştır
    - name: Run canli_tv.php
      run: php canli_tv.php

    - name: Run filmler.php
      run: php filmler.php

    - name: Run diziler.php
      run: php diziler.php

    # 4. Değişiklik varsa commit ve push
    - name: Commit and push if changed
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        # Dosyalar varsa ekle
        [ -f canli_tv.m3u ] && git add canli_tv.m3u
        [ -f filmler.m3u ] && git add filmler.m3u
        [ -f diziler.m3u ] && git add diziler.m3u

        # Değişiklik varsa commit et
        if git diff --cached --quiet; then
          echo "Mevcut M3U listelerinde değişiklik yok, commit atılmayacak."
          exit 0
        fi

        echo "Yeni M3U listeleri bulundu, commit atılıyor..."
        git commit -m "Update M3U lists [skip ci]"
        git push
