name: Generate M3U List

on:
  schedule:
    - cron: '0 */12 * * *' # 12 saatte bir otomatik
  workflow_dispatch:      # Manuel tetikleme için

jobs:
  build:
    runs-on: ubuntu-latest
    
    # YENİ: Depoya yazma izni ekler. Bu, "permission denied" hatasını çözer.
    permissions:
      contents: write

    steps:
    # Bu adımda bir değişiklik yok
    - name: Checkout
      uses: actions/checkout@v4

    # Bu adımda bir değişiklik yok
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    # Bu adımda bir değişiklik yok, m3u dosyanız burada oluşturuluyor
    - name: Run generator
      run: php m3u-generator.php

    # GÜNCELLENDİ: Bu adım artık daha akıllı ve hataya dayanıklı
    - name: Commit & Push output
      run: |
        # Git kullanıcı bilgilerini ayarla
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        # 1. KONTROL: 'm3u-generator.php' scripti 'output.m3u' dosyasını oluşturdu mu?
        # Eğer dosya yoksa, mesaj yaz ve hatasız çık.
        if [ ! -f "output.m3u" ]; then
          echo "output.m3u dosyası 'm3u-generator.php' tarafından oluşturulmadı. İşlem yapılmayacak."
          exit 0
        fi

        # Dosya varsa, git'e ekle
        git add output.m3u
        
        # 2. KONTROL: Dosyanın içeriğinde bir önceki sürüme göre değişiklik var mı?
        # Eğer değişiklik yoksa, mesaj yaz ve hatasız çık.
        if git diff --staged --quiet; then
          echo "Mevcut M3U listesinde değişiklik bulunamadı."
          exit 0
        fi
        
        # Sadece hem dosya varsa hem de içinde değişiklik varsa commit at ve push yap
        echo "Değişiklikler bulundu, depoya gönderiliyor..."
        git commit -m "Update M3U output [skip ci]"
        git push