# Bu dosyada herhangi bir değişiklik yapmanıza gerek yok.
# Sadece .gitignore dosyasını eklemeniz yeterli.
# Bu dosya referans olması için eklenmiştir.

name: rec yeni Playlists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  generate-m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: pip install requests firebase-admin

    - name: Create Config Files
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        FIREBASE_UID: ${{ secrets.FIREBASE_UID }}
      run: |
        cd scripts
        python firebase-auth.py
        python get-api-config.py

    - name: Generate M3U playlists
      run: |
        php scripts/generate-m3u.php

    - name: Commit and push M3U playlists
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add scripts/*.m3u

        if ! git diff --cached --quiet; then
          echo "✅ Değişiklikler tespit edildi, commit ve push yapılıyor..."
          git commit -m "Auto-update M3U playlists in /scripts ($(date +'%Y-%m-%d %H:%M'))"
          git push
        else
          echo "ℹ️ Dosyalarda kayda değer bir değişiklik bulunamadı, commit atlanıyor."
        fi